apiVersion: valhalla.itayankri/v1alpha1
kind: Valhalla
metadata:
  name: example
spec:
  pbfUrl: https://download.geofabrik.de/europe/andorra-latest.osm.pbf
  minReplicas: 1
  maxReplicas: 3
  resources:
    requests:
      cpu: "1000m"
      memory: "100Mi"
    limits:
      cpu: "1500m"
      memory: "150Mi"
  persistence:
    storage: "100Mi"
    storageClassName: nfs-csi