name: Integration test

inputs:
  goVersion:
    description: 'Golang version'
    default: 1.19.2
    required: false

runs:
  using: "composite"
  steps:
  - name: Install Go
    uses: actions/setup-go@v2
    with:
      go-version: ${{ inputs.goVersion }}
  - name: Setup Golang caches
    uses: actions/cache@v3
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-golang-
  - name: Check out code into the Go module directory
    uses: actions/checkout@v2
    with:
      ref: ${{ github.event.pull_request.head.sha }}
  - uses: azure/setup-helm@v3
    with:
      version: 3.7.1
  - name: Install Kind
    uses: helm/kind-action@v1.3.0
    with:
      install_only: true
  - name: Run tests
    run: |
      export GOPATH=$HOME/go
      export PATH=$PATH:$GOPATH/bin
      cat /etc/docker/daemon.json | jq '. += {"storage-driver":"vfs"}' > daemon.json
      sudo rm /etc/docker/daemon.json
      sudo mv daemon.json /etc/docker/daemon.json
      sudo systemctl restart docker.service
      kind create cluster --name valhalla --config examples/kind-config.yaml
      kubectl create -f https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/example/nfs-provisioner/nfs-server.yaml
      helm repo add csi-driver-nfs https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      helm install csi-driver-nfs csi-driver-nfs/csi-driver-nfs --namespace kube-system --version v3.1.0
      kubectl create -f https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/example/storageclass-nfs.yaml
      kubectl wait --for condition=Available deployment/nfs-server --timeout=60s
      sleep 5
      kubectl logs $(kubectl get pods | grep nfs | awk '{print $1}')
      make install deploy
      kubectl -n valhalla-system wait --for condition=Available deployment/valhalla-controller-manager --timeout=60s
      make integration-test